services:
  php-fpm:
    build: .
    volumes:
      - .:/var/www/html
    user: "root:root"
    depends_on:
      - mysql

  nginx:
    image: nginx:stable-alpine3.20-perl
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    user: "root:root"

  mysql:
    image: mysql:8.0.41-bookworm
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=perfume_Api
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    user: "root:root"
    volumes:
      - perfume_api:/var/lib/mysql

  redis:
    image: redis:bookworm
    ports:
      - "6379:6379"
    user: "root:root"
    
volumes:
  perfume_api:

