services:
  php-fpm:
    build: .
    volumes:
      - .:/var/www/html
    user: "root:root"
    depends_on:
      - mysql

  nginx:
    image: nginx:v1
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    user: "root:root"

  mysql:
    image: mysql:8.0.41-bookworm
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=perfume_Api
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    user: "root:root"
    volumes:
      - perfume_api:/var/lib/mysql

  redis:
    image: redis:bookworm
    ports:
      - "6379:6379"
    user: "root:root"

  composer:
    image: composer:2.8.8
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - php-fpm
    command: >
      sh -c "adduser -D composeruser &&
      chown -R composeruser:composeruser /app &&
      su - composeruser -c 'composer require predis/predis'"

volumes:
  perfume_api:

