services:
  php-fpm:
    build: .
    volumes:
      - .:/var/www/html
    user: "root:root"
    networks:
        perfume_api_default:
            ipv4_address: 10.5.0.5
    depends_on:
      - mysql

  nginx:
    image: nginx:stable-alpine3.20-perl
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
        perfume_api_default:
            ipv4_address: 10.5.0.6
    user: "root:root"

  mysql:
    image: mysql:8.0.41-bookworm
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=perfume_Api
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    user: "root:root"
    networks:
        perfume_api_default:
            ipv4_address: 10.5.0.7
    volumes:
      - perfume_api:/var/lib/mysql

  redis:
    image: redis:bookworm
    networks:
        perfume_api_default:
            ipv4_address: 10.5.0.8
    ports:
      - "6379:6379"
    user: "root:root"

volumes:
  perfume_api:
networks:
    perfume_api_default:
        driver: bridge
        name: perfume_api_default
        ipam:
            config:
                - subnet: 10.5.0.0/16
                  gateway: 10.5.0.1
